repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.3.5'
    hooks:
      - id: ruff
        args: [--fix,  --exit-non-zero-on-fix]
      - id: ruff-format
  - hooks:
      - args:
          - -i
          - "2"
        id: beautysh
        language_version: python3
    repo: https://github.com/lovesegfault/beautysh
    rev: v6.2.1
