name: Deploy deb/rpm to s3 repo
on:
  push:
    branches: main
  pull_request:
jobs:
  pkgs:
    name: ${{ matrix.pkg }}
    strategy:
      fail-fast: false
      matrix:
        pkg: [deb, rpm]
    environment: aws
      permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install deps
      run: pip install gitpython docker
    - name: Download
      run: python download.py
    - name: Build and sign
      run: python build.py ${{ matrix.pkg }}
    - name: sanity check
      run: python test.py ${{ matrix.pkg }}
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::260760892802:role/dvc-s3-repo-deploy
    - name: Upload
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      env:
        GPG_ITERATIVE_ASC: ${{ secrets.GPG_ITERATIVE_ASC }}
        GPG_ITERATIVE_PASS: ${{ secrets.GPG_ITERATIVE_PASS }}
      run: python upload.py ${{ matrix.pkg }}
