name: Deploy deb/rpm to s3 repo
on:
  push:
    branches: master
  pull_request: {}
jobs:
  pkgs:
    name: ${{ matrix.pkg }}
    strategy:
      fail-fast: false
      matrix:
        pkg: [deb, rpm]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install deps
      run: pip install gitpython docker
    - name: Download
      run: python download.py
    - name: Build and sign
      run: python build.py ${{ matrix.pkg }}
    - name: sanity check
      run: python test.py ${{ matrix.pkg }}
    - name: Upload
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GPG_ITERATIVE_ASC: ${{ secrets.GPG_ITERATIVE_ASC }}
        GPG_ITERATIVE_PASS: ${{ secrets.GPG_ITERATIVE_PASS }}
      run: |
        mkdir ~/.aws
        echo "[profile iterative]" >> ~/.aws/config
        echo "region = us-east-2" >> ~/.aws/config
        echo "[iterative]" >> ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        python upload.py ${{ matrix.pkg }}
