name: Deploy deb/rpm to s3 repo
on:
  push:
    branches: master
  schedule:
    - cron: '0 */12 * * *'
jobs:
  deb:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GPG_ITERATIVE_ASC: ${{ secrets.GPG_ITERATIVE_ASC }}
        GPG_ITERATIVE_PASS: ${{ secrets.GPG_ITERATIVE_PASS }}
      run: |
        mkdir ~/.aws
        echo "[profile iterative]" >> ~/.aws/config
        echo "region = us-east-2" >> ~/.aws/config
        echo "[iterative]" >> ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        ./deploy.sh ubuntu deb
  rpm:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GPG_ITERATIVE_ASC: ${{ secrets.GPG_ITERATIVE_ASC }}
        GPG_ITERATIVE_PASS: ${{ secrets.GPG_ITERATIVE_PASS }}
      run: |
        mkdir ~/.aws
        echo "[profile iterative]" >> ~/.aws/config
        echo "region = us-east-2" >> ~/.aws/config
        echo "[iterative]" >> ~/.aws/credentials
        echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
        echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
        ./deploy.sh fedora rpm
